package br.eti.ljr.sn.templatesrv.domain;
// Generated 15/05/2020 16:28:32 by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Administrativa generated by hbm2java
 */
@Entity
@Table(name = "ADMINISTRATIVA", schema = "CLICK")
public class Administrativa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String parametro;
	private String valor;

	public Administrativa() {
	}

	public Administrativa(String parametro) {
		this.parametro = parametro;
	}

	public Administrativa(String parametro, String valor) {
		this.parametro = parametro;
		this.valor = valor;
	}

	@Id

	@Column(name = "PARAMETRO", unique = true, nullable = false, length = 20)
	public String getParametro() {
		return this.parametro;
	}

	public void setParametro(String parametro) {
		this.parametro = parametro;
	}

	@Column(name = "VALOR", length = 200)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

}
