package br.eti.ljr.sn.templatesrv.domain;
// Generated 15/05/2020 16:28:32 by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Permissao generated by hbm2java
 */
@Entity
@Table(name = "PERMISSAO", schema = "CLICK")
public class Permissao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private PermissaoId id;
	private Boolean autorizado;

	public Permissao() {
	}

	public Permissao(PermissaoId id) {
		this.id = id;
	}

	public Permissao(PermissaoId id, Boolean autorizado) {
		this.id = id;
		this.autorizado = autorizado;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "chave", column = @Column(name = "CHAVE", nullable = false, length = 6)),
			@AttributeOverride(name = "codPessoa", column = @Column(name = "COD_PESSOA", nullable = false, precision = 14, scale = 0)),
			@AttributeOverride(name = "codSistema", column = @Column(name = "COD_SISTEMA", nullable = false, precision = 9, scale = 0)) })
	public PermissaoId getId() {
		return this.id;
	}

	public void setId(PermissaoId id) {
		this.id = id;
	}

	@Column(name = "AUTORIZADO", precision = 1, scale = 0)
	public Boolean getAutorizado() {
		return this.autorizado;
	}

	public void setAutorizado(Boolean autorizado) {
		this.autorizado = autorizado;
	}

}
