package br.eti.ljr.sn.templatesrv.domain;
// Generated 15/05/2020 16:28:32 by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PermissaoId generated by hbm2java
 */
@Embeddable
public class PermissaoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String chave;
	private long codPessoa;
	private int codSistema;

	public PermissaoId() {
	}

	public PermissaoId(String chave, long codPessoa, int codSistema) {
		this.chave = chave;
		this.codPessoa = codPessoa;
		this.codSistema = codSistema;
	}

	@Column(name = "CHAVE", nullable = false, length = 6)
	public String getChave() {
		return this.chave;
	}

	public void setChave(String chave) {
		this.chave = chave;
	}

	@Column(name = "COD_PESSOA", nullable = false, precision = 14, scale = 0)
	public long getCodPessoa() {
		return this.codPessoa;
	}

	public void setCodPessoa(long codPessoa) {
		this.codPessoa = codPessoa;
	}

	@Column(name = "COD_SISTEMA", nullable = false, precision = 9, scale = 0)
	public int getCodSistema() {
		return this.codSistema;
	}

	public void setCodSistema(int codSistema) {
		this.codSistema = codSistema;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PermissaoId))
			return false;
		PermissaoId castOther = (PermissaoId) other;

		return ((this.getChave() == castOther.getChave()) || (this.getChave() != null && castOther.getChave() != null
				&& this.getChave().equals(castOther.getChave()))) && (this.getCodPessoa() == castOther.getCodPessoa())
				&& (this.getCodSistema() == castOther.getCodSistema());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getChave() == null ? 0 : this.getChave().hashCode());
		result = 37 * result + (int) this.getCodPessoa();
		result = 37 * result + this.getCodSistema();
		return result;
	}

}
